const mongoose = require('mongoose');

// Matches the spots structure from frontend data/backend.js
const spotSchema = new mongoose.Schema({
  id: Number,
  name: String,
  location: String,
  fee: String,
  timing: String,
  closed: String,
  rating: String,
  img: String,
});

// Hotel structure matching plan.html hotel list
const hotelSchema = new mongoose.Schema({
  name: String,
  address: String,
  rating: String,
  price: Number,
  img: String,
  stars: Number,
});

// Expense tracking
const expenseSchema = new mongoose.Schema({
  category: { type: String, enum: ['food', 'transport', 'activity', 'other'], required: true },
  amount: { type: Number, required: true },
  note: String,
  date: { type: Date, default: Date.now },
});

// Itinerary entry
const itinerarySchema = new mongoose.Schema({
  day: Number,
  activities: [String],
  morning: String,
  afternoon: String,
  evening: String,
});

const tripSchema = new mongoose.Schema(
  {
    // Who owns this trip
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    // Core trip inputs from index.html form
    startLocation: { type: String, required: true },
    destination: { type: String, required: true },
    startDate: { type: String, required: true },
    endDate: { type: String, required: true },
    budget: { type: Number, required: true },
    people: { type: Number, default: 1 },

    // Computed fields
    days: { type: Number },

    // Selected spots from the "Customise Route" step (form.js renderSpot)
    selectedSpots: [spotSchema],

    // Selected hotel from the "Stay Preference" step (form.js renderHotel)
    selectedHotel: hotelSchema,

    // Budget breakdown generated by backend
    budgetBreakdown: {
      perPersonPerDay: Number,
      perPerson: Number,
      totalBudget: Number,
      budgetLabel: String,
      accommodation: Number,
      food: Number,
      transport: Number,
      activities: Number,
      emergency: Number,
    },

    // Weather data fetched from OpenWeatherMap
    weather: {
      temp: Number,
      description: String,
      icon: String,
    },

    // Destination image from Unsplash
    destinationImage: { type: String, default: '' },

    // Itinerary - day-wise activities (added by user in plan.html)
    itinerary: [itinerarySchema],

    // AI-generated itinerary from Gemini
    aiItinerary: [
      {
        day: Number,
        morning: String,
        afternoon: String,
        evening: String,
      },
    ],

    // Expense tracking
    expenses: [expenseSchema],

    // Share link (read-only access)
    shareLink: { type: String, unique: true, sparse: true },

    // Status of the trip
    status: {
      type: String,
      enum: ['planned', 'ongoing', 'completed'],
      default: 'planned',
    },
  },
  { timestamps: true }
);

// Auto-compute days from dates before saving
tripSchema.pre('save', function (next) {
  if (this.startDate && this.endDate) {
    const start = new Date(this.startDate);
    const end = new Date(this.endDate);
    const diff = Math.ceil((end - start) / (1000 * 60 * 60 * 24));
    this.days = diff > 0 ? diff : 1;
  }
  next();
});

module.exports = mongoose.model('Trip', tripSchema);
